name: deep-storm
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - bokeh=0.13.0
  - ca-certificates=2019.10.16
  - certifi=2018.8.24
  - click=7.0
  - cloudpickle=1.2.2
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=0.19.2
  - dask-core=0.19.2
  - decorator=4.4.1
  - distributed=1.23.2
  - freetype=2.8.1
  - h5py=2.7.1
  - hdf5=1.10.1
  - heapdict=1.0.1
  - icc_rt=2019.0.0
  - icu=58.2
  - imageio=2.4.1
  - intel-openmp=2019.5
  - jinja2=2.10.3
  - jpeg=9b
  - kiwisolver=1.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - locket=0.2.0
  - markupsafe=1.0
  - matplotlib=2.1.1
  - mkl=2018.0.3
  - msgpack-python=0.5.6
  - networkx=2.4
  - olefile=0.46
  - openssl=1.0.2t
  - packaging=19.2
  - pandas=0.23.4
  - partd=1.0.0
  - pillow=5.1.0
  - pip=9.0.1
  - psutil=5.4.7
  - pyparsing=2.4.2
  - pyqt=5.6.0
  - python=3.5.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pywavelets=1.0.0
  - qt=5.6.2
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - sip=4.18.1
  - sortedcontainers=2.0.5
  - sqlite=3.30.1
  - tblib=1.5.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=5.1.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wincertstore=0.2
  - xz=5.2.4
  - yaml=0.1.7
  - zict=1.0.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - argparse==1.4.0
    - bleach==1.5.0
    - enum34==1.1.6
    - html5lib==0.9999999
    - keras==2.1.3
    - markdown==3.1.1
    - numpy==1.17.4
    - pip==19.3.1
    - protobuf==3.10.0
    - pyyaml==5.1.2
    - scipy==1.3.2
    - setuptools==41.6.0
    - six==1.13.0
    - tensorflow-gpu==1.4.0
    - tensorflow-tensorboard==0.4.0
    - werkzeug==0.16.0
    - wheel==0.33.6

