version: '3'

services:
  wrf:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - WRF_NUM_PROCESSORS=4
    restart: unless-stopped 